### ISSUE TITLE
The first sentence in section 6.3 says:

### ISSUE THREAD

**Issue by emmanuelmoon** [rauschma/exploring-js#57]
The first sentence in section 6.3 says:

     When you have a question about a JavaScript, a web search usually helps.

I suspect you meant to write, "...a question about JavaScript, a web...".

This issue still remains in 2024.

_Originally posted by @ttmc in https://github.com/rauschma/exploring-js/issues/32#issuecomment-1341653862_

**Comment by rauschma** [comment]
@emmanuelmoon Thanks! A fix is online now (and part of the next release on Payhip).
